#include "sys.h"
#include "delay.h"
#include "usart.h"
#include "led.h"
#include "timer.h"
#include "lcd.h"
#include "FreeRTOS.h"
#include "task.h"
#include "stdio.h"
#include "can.h"
#include "RemoteControl.h"
#include "Mputask.h"
void BSP_Init();
void StartTask();
